#!/usr/bin/env ansible-playbook

- name: setup probehost2 nodes
  hosts: nodes
  roles:
    - pull_deps
    - hostname
    - pull_probehost2
    - setup_user
    - customize
    - systemd
    - test_avail

  post_tasks:
    - name: finished
      debug:
        msg: "node setup finished"