---

- name: apply config from inventory
  lineinfile:
    path: /etc/systemd/system/probehost2.service
    regexp: '^ExecStart='
    line: "ExecStart=/bin/probehost2 --logfilepath {{ logpath }} --port {{ runport }}"
